= Building a Knowledge Graph

== Why a Knowledge Graph?

There are two main motivations.

First, we would like to be create a reference database of "knowledge" that will map out the themes in digital enlightenment. This is interesting in its own right, for example in order to allow to modularise content for the day course or workshops. An extensive topic database can be used as a reference for creating "bespoke" courses, or for extending/modifying "standard" courses.

Second, we want to build an online learning platform with the following attributes:
//list
[loweralpha]
. it will contain all topics for digital enlightenment
. the set of topics that a user will explore will depend on who the user is
. the delivery method (learning experience) will adjust to who the user is

A topic database will provide the framework upon which online courses can be based.

CAVEAT: We want the journey through the space of topics to be flexible. Hurrah! Use a graph!

== What is a graph?

//hide
[source,cypher]
----
CREATE

//Fields
(ct:Field {name:"Comp. Thinking"}),
(data:Field {name:"Data"}),
(web:Field {name:"Web"}),


(html:Topic {name:"html"}),
(html)-[:RT]->(web),
(js:Topic {name:"JavaScript"}),
(js)-[:related]->(web),
(js)-[:related]->(ct),

(python:Topic {name:"Python"}),
(python)-[:related]->(data),
(python)-[:related]->(ct),

(cloud:Topic {name:"Cloud"}),
(cloud)-[:related]->(data),
(cloud)-[:related]->(web);

MATCH n RETURN n as node;

----

//graph

== Why is it useful?

//list
. Easy to explore relationships between topics (visually)
. Natural way for mapping out relationships between topics
. Graph theory to help us pick journeys though digital enlightenment

== Strategy/Approach

We can use the Neo4j technology and the cypher language (graph query language) to create and explore the knowledge graph. Neo4j has paid-for services but so far I've been using the free tools locally on my machine. All scripts are uploaded on my decoded google drive.

//list

. Obtain a list of topics (by.....)

== Where are we?

//list
. List of topics (212 and counting)
. Just under 4300 relationships between them
